kind: Service
apiVersion: v1
metadata:
  name: golang-app
spec:
  type: ClusterIP
  selector:
    app: golang-app
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 8080
    # nodePort: 32000

