apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-deployment
spec:
  selector:
    matchLabels:
      app: golang-app
  replicas: 3
  strategy:
    type: "RollingUpdate"
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: golang-app
    spec:
      containers:
      - name: golang
        image: kahootali/golang-sample-app:v1.2.21
        ports:
        - containerPort: 8080
          name: tcp